---
ID: "aa850cda-bff2-4a47-a14b-6f3653256781"
Parent: "8bc1cec9-0582-4569-a7c5-b34e3d4256cf"
Template: "8bc1cec9-0582-4569-a7c5-b34e3d4256cf"
Path: /sitecore/templates/Project/XMBoys/Related Content/Call To Action Row Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {77E925DF-92A5-49AE-B54A-C37CF62DD201}
    {8BC1CEC9-0582-4569-A7C5-B34E3D4256CF}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "49efdee4-b948-4565-98d6-e76fe9fd4bea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T044908Z
