---
ID: "c8b145a4-29d6-47fc-a766-20e05c14ee84"
Parent: "dbd7d0be-5f58-4191-a3c0-a22f660fb79d"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/XMBoys/XMBoys/Presentation/Headless Variants/Call To Action Row/Default
BranchID: "1fa71c7e-5970-4681-bf69-82526f18524b"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D3CF864D-6016-448A-98EF-39780C2D5E46}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T045428Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0dc7ecc9-02c9-4090-822c-80932e3ed662"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T045428Z
