---
ID: "99c1a516-cb9e-449f-8201-57cc47455167"
Parent: "3e64d214-49d1-46ad-81c1-76ba1092f82e"
Template: "3e64d214-49d1-46ad-81c1-76ba1092f82e"
Path: /sitecore/templates/Project/XMBoys/Primary Content/Rendering Parameters/Hero Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "37c7e7e0-e96c-4a68-8c1f-4bc691c42ad3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\paul.bonilla@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T185002Z
