---
ID: "05713bf0-6190-4465-a7c4-58405a58e605"
Parent: "c23afb2c-5a1b-44b6-8aeb-580a10874670"
Template: "ab987746-78b0-4773-a8de-b295c493b7a4"
Path: /sitecore/content/XMBoys/XMBoys/Settings/Standard Values
BranchID: "30e7b26c-77ee-4e15-ad13-a0cffc31f4b4"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{1F2F22FA-2B6C-42BD-966A-DED58F4851ED}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T031617Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e90b9b36-02ed-4ac2-a4ac-42b4c0dc2410"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T031617Z
