---
ID: "b30233d3-7021-4fc4-893c-3c4abdfadd6e"
Parent: "8871d114-f73c-4ad8-afbe-dba5d4f2bdb5"
Template: "8871d114-f73c-4ad8-afbe-dba5d4f2bdb5"
Path: /sitecore/templates/Project/XMBoys/Related Content/Rendering Parameters/Call To Action Row/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3ec13020-40d0-4486-96db-5ff558647b0d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T044907Z
